### PR TITLE
WIP: Add Esperanto translation

### PR DESCRIPTION
**Pull request by jorgesumle**
Right now the translation progress is 134 of 514 (26%). I think the game cannot display some Esperanto letters (ĉ, ĝ, ĥ, ĵ, ŝ, ŭ), as shown in the image below. I installed the game locally to see how the translation looked like in-game, and noticed that when there was an special character the translation didn't show up, or only showed up until a weird character began.
Bildschirmfoto zu 2021-01-21 17-04-58

### CODE REVIEW

**Comment by onpon4** [comment]
Yes, you'll have to include a new font which Esperanto can use (it should go in the "data" directory), then reference it by "translating" `"data/TakaoPGothic.ttf"` to the name of the font you've added.

🕵️

**Comment by jorgesumle** [comment]
Thanks, Emmy. For some reason, it still isn't fixed after that, or maybe I'm a mess compiling. I created a folder so that the font has only one license text in its directory (otherwise, it's a bit confusing). There are many fonts supporting Esperanto characters. I just picked a random one from the list I found on [this article](http://www.esperantojugend.at/esperanto/2016/01/esperantaj-tiparoj-ce-fontlibrary-org/), I'm not an expert in fonts, so I hope the font I chose is good enough.

When I have more free time, I'll finish the translation.

**Comment by onpon4** [comment]
> For some reason, it still isn't fixed after that, or maybe I'm a mess compiling.

~~My guess is that you probably have Project: Starfighter installed and have built a standard build, causing it to use the data from that Starfighter install (which doesn't have the new font). You can fix that for the purpose of your testing by creating a run-in-place build:~~

```
./configure SF_RUN_IN_PLACE=1
make clean
make
```

~~Otherwise, do you see an error or warning printed to the terminal when you run the game?~~

EDIT: Ah, actually

Ignore that. The problem here is that you don't have font / unicode support enabled, so it's using the old sprite font. (I just noticed that in the screenshot.) Make sure you have Pango and SDL2_ttf installed and recompile.

🕵️

**Comment by jorgesumle** [comment]
Yep, you're right, I was missing dependencies. The font I picked looks too bold. I don't quite like the how it looks in-game, it looked better in the website preview. I'll have to pick another one.
Bildschirmfoto zu 2021-01-21 19-35-54

**Comment by onpon4** [comment]
It might be worth double-checking to see if TakaoPGothic works. It might. I seem to recall hearing that ō is the only major accented character it's missing.

🕵️

**Comment by jorgesumle** [comment]
> It might be worth double-checking to see if TakaoPGothic works

Yeah, it looks good. Fortunately, there is no ō in Esperanto. Sorry for the mess, to be honest, I thought I had all the packages installed, as the game worked fine.

Bildschirmfoto zu 2021-01-21 19-44-03

**Comment by onpon4** [comment]
Haha, yes. It actually shows that it's compiling without font support but it's one of many messages and easy to miss. The reason it supports working without font support is just on the off-chance that someone can't use Pango or SDL_ttf for some reason.

Perhaps those "Note:" texts could be changed to "WARNING:" texts. Would make them easier to see.

🕵️

**Comment by jorgesumle** [comment]
> The reason it supports working without font support is just on the off-chance that someone can't use Pango or SDL_ttf for some reason.

That is perfectly reasonable. The problem was me in this case, because I didn't follow the README instructions.

I needed to change the names a bit (for example, WEAPons COrporation → ARMila KORPoracio), so that word games like "WEEPCO" and other stuff can be better understood. I guess it's fine as long as everything is consistent. I think there are a bunch of things that cannot be translated, like some headings in the credits, the "Version" text from the title screen (in Esperanto it would be 'versio'). Maybe you have a reason not to make these things translatable, I don't know.

**Comment by onpon4** [comment]
Changing WEAPCO's name is fine by me if it suits the translation better. :slightly_smiling_face:

🕵️

**Comment by jorgesumle** [comment]
OK, I see that some things are not easy to translate (for example, there is a `gameover.png` file), which is understandable if the original game was only targeted at English-speaking countries. When I finish, I'll squash the commits and tell you it's ready to merge.

**Comment by jorgesumle** [comment]
The SAVE text ("KONSERVI") doesn't look center-aligned when translated. Maybe too many characters?

Bildschirmfoto zu 2021-01-28 22-01-36

**Comment by onpon4** [comment]
Oh wow! Taking a look, the text is given an absolute position that leads to centering in English. The text drawing doesn't support actual centering, it only supports drawing text in the exact center of the surface being drawn to. Since that won't work for centering on all the buttons, I'll change it to be left-aligned.

🕵️

**Comment by onpon4** [comment]
May I ask why this is closed now? It seems you made a lot of progress with this.

🕷️

**Comment by jorgesumle** [comment]
I'm going to therapy right now, so I'm not sure when or if I'll be able to finish it. You can merge what's already translated if you want: it's a good translation.

**Comment by onpon4** [comment]
Okey dokey! Fair enough. Take care of your mental health, and thank you for the contribution! 🙂

🕵️

**Pull request merged**
