### PR TITLE
build: fix MacOS build

### PR DESCRIPTION
**Pull request by igilham**
Use the new autogen.sh script to run aclocal and libtoolize before
autoreconf.

Possible partial solution to #3.

### CODE REVIEW

**Comment by igilham** [comment]
Fixes missing linker flag on MacOS.

Still has the following make error during build:

```
Making all in misc
make[2]: Nothing to be done for `all'.
make[2]: *** No rule to make target `locale/en/LC_MESSAGES/pr-starfighter.mo', needed by `all-am'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by igilham** [comment]
The step to build the locale was strangely missing from my README. I've moved the step into `autogen.sh` and fixed an issue finding `msgfmt` (a gettext tool) from the Python code.

The build now completes.

The binary does not run:

```shell
./starfighter.sh 
Current directory "/Users/gilhai01/code/starfighter/src"
ERROR: TTF_OpenFont: Couldn't open data/TakaoPGothic.ttf
Thank You for playing Starfighter

ll data/
total 6.0M
-rw-r--r-- 1 gilhai01 287753940 6.0M Mar  5 18:20 TakaoPGothic.ttf
-rw-r--r-- 1 gilhai01 287753940 1.6K Mar  6 09:53 credits.txt
-rw-r--r-- 1 gilhai01 287753940  21K Mar  5 18:20 ipa_font_license.txt
```

**Comment by igilham** [comment]
It looks like TTF font loading in `gfx.c` assumes we're in the root directory, but the XCode compatibility code in `Starfighter.c` changes directory on a Mac, breaking the assumption.

Commenting out [the line](https://github.com/pr-starfighter/starfighter/blob/master/src/Starfighter.c#L68) fixes this issue and allows the application to load. I don't know enough about the MacOS platform and XCode to say if this will break the relative path support.

**Comment by onpon4** [comment]
OK, so I'm not opposed to autogen.sh but things like autoreconf are not supposed to be used by an end-user compiling releases. In releases of the source code the configure script is to just be included so that all an end-user compiling needs to do is run that configure script (not needing Autoconf, Autumake, or pkg-config as dependencies). So any extra stuff that needs to be done in MacOS needs to be always included in and handled by the configure script no matter what. I don't believe your autogen.sh script does that.

**Comment by igilham** [comment]
Okay, that sounds like a sensible convention. I've never used the autotools stuff before so this is just my attempt to learn it enough to fix a problem. These settings and commands work on my Mac. Can you suggest a better way to organise them for end-users?

**Comment by onpon4** [comment]
I honestly don't know for sure because I don't fully understand what the MacOS conditional in autogen.sh is doing (lack of familiarity with MacOS in particular). But most likely you would move that to configure.ac somehow, or possibly Makefile.am. The important thing is that Mac users compiling releases will *not* be running autogen.sh; someone putting together the release (probably me, on a Linux computer) will be doing so.

Autotools and Automake have a whole bunch of facilities for doing stuff like this, although their documentation is rather poor and hard to navigate. I'm sick at the moment but if you haven't figured something out by the time I feel better I can look into it for you.

**Comment by igilham** [comment]
I can explain that to some degree.

First, we run `libtoolize`. On MacOS, the `libtoolize` command has a different name (`glibtoolize`) but it's the same thing you'd have on Linux. I wasn't sure if the generated files should be committed so I just added them to `.gitignore` to be safe. I'm not actually certain that we need to use the extra `libtool` stuff I added at all.

Second, I've had problems with `gettext` on the `PATH`. `msgfmt` is a `gettext` tool called by the locale builder Python script. As far as I can tell, the Mac doesn't ship with this tool. This is probably because the supplied version of `gettext` comes from FreeBSD on a Mac. A common solution to this is to use Homebrew to install the GNU version. This typically doesn't get added to the `PATH` because it might break certain things in the OS, so we detect it if it's present and update the `PATH` so the Python script can find it. This could be handled completely in the Python script.

I mostly followed [this guide](https://digitalleaves.com/blog/2017/12/build-cross-platform-c-project-autotools/) to learn how to do this.

I might keep working on this a bit following your suggestions. Please don't feel like you need to respond or help while you're trying to get better.

**Comment by onpon4** [comment]
OK, so as I said before, build.py is just used as a part of setting up a distribution, or for developers who are compiling straight from the Git repo. So it's not a problem if build.py fails on MacOS necessarily, as long as a MacOS developer can work around it reasonably. Users compiling releases will never have to worry about that problem because releases come with pre-built locales. (They're just not included in the repo since it's unnecessary and a waste of space; and on that note, yes, autogenerated files that can be easily reproduced should always be `.gitignore`'d.)

If the path they're built to doesn't work for Mac, that should be handled by configure.ac or Makefile.am or C preprocessor inserts, as appropriate. The exact same ./configure should work on Linux, Windows, Mac, or any other system as long as the dependencies are satisfied, regardless of where the ./configure script was generated.

I still don't understand why you changed locale/build.py the way you did, but if it has to do with moving the locale builds for a platform-specific nuance, that should be done with the already built files (actually, copying should be used). Probably in make install, unless you need to do something for run-in-place too.

**Comment by onpon4** [comment]
Just a heads-up, I made some tweaks to the Autoconf setup so you'll want to pull the master branch before adding in stuff for handling MacOS to them (so you don't have to resolve conflicts afterward).

**Comment by igilham** [comment]
Thanks for the head's up. I've rebased the branch. I'll experiment a little more and try to get it to work with less random changes. I wasn't aware that the `configure` script is intended to be cross-platform so I'll try to get it working from there.

**Comment by igilham** [comment]
@onpon4 Okay, I think I'm done. I've got it down to a smaller set of changes, made sure the MacOS detection works in the `configure` script and documented the work-around required to run `build.py`.

The only code change is to comment out a `chdir` call which breaks the normal program assumptions around where the `cwd` is when loading a font.

I really appreciate your help in figuring out how to do this.

**Comment by onpon4** [comment]
OK, so code-wise, the code you modified is something meant to work on .app bundles. Have you confirmed that building and running a .app bundle works? I understand that those bundles are the usual way to distribute MacOS binaries, unless that's changed.

**Comment by onpon4** [comment]
Also, with that line removed, the line following it is inaccurate.

Is there a more proper directory to cd to? Or does MacOS automatically change cwd to something sensible within the .app file? And if the latter, might there be a simpler way to get Starfighter to do nothing than to ask for a directory it isn't using? (Sorry for all the questions.)

**Comment by igilham** [comment]
I don't know much about distributing software on a Mac. Commercial packages are often in a `.dmg` image and command-line tools are often more similar to Linux, with files in `/opt` or `/usr/local` etc.

it might be best to leave that line in and change the path to the font to an absolute path based on the local runtime environment. We would have to work out which APIs to call on each platform to do that though.

**Comment by onpon4** [comment]
So you commented that out because something didn't work, right? What was the path it was CD'ing to and what was the problem exactly? You mentiton fonts but I don't really understand what you're talking about.

**Comment by igilham** [comment]
The font thing was this error, coming from [this line of code](https://github.com/pr-starfighter/starfighter/blob/d96c8327e4f1fd135333ceddabc5c3d0ec804ca5/src/gfx.c#L116):

```
./starfighter.sh 
Current directory "/Users/gilhai01/code/starfighter/src"
ERROR: TTF_OpenFont: Couldn't open data/TakaoPGothic.ttf
Thank You for playing Starfighter
```

The line I commented out changes the working directory to `src`, so the relative path being opened to read the font file from (`data/TakaoGothic.ttf`) is wrong at that point.

Commenting the line out is the easiest way to make the app run straight from the command line but it may break app bundles, as you have said. Changing the font path to an absolute path would be one way to fix it without breaking the bundle but it might not be the simplest way.

**Comment by onpon4** [comment]
Ah, OK, so it's not supposed to be cd'ing to the src directory, but the directory above it. And that's not specific to fonts, it's all Starfighter's data.

I suspect that the problem is it needs the starfighter binary to be a directory up, rather than in src. If that's too hard, you can append "../" to the path and that should do the trick. But I assume that actually having the starfighter binary a directory up (in the directory where the data directory is) would be more ideal. (In fact it's what's recommended in the readme for run-in-place builds.)

In any case, that chdir needs to be there. It's just that where it's changing to needs to be adjusted.

**Comment by igilham** [comment]
I feel like this is best solved by doing nothing in the code and documenting the error that a user might see. I've pushed a couple of changes to that effect. It runs on my machine if I move the binary to the repo root; it just wasn't very clear that moving it is necessary to get it to run correctly.

What do you think?

**Comment by onpon4** [comment]
OK, I've pulled into my own macos branch and made some changes:

https://github.com/pr-starfighter/starfighter/tree/macos

Can you make sure it still works with the changes I made? I believe it should. If not let me know where it failed.

**Comment by onpon4** [comment]
Oh, and can you check one thing? If you leave starfighter in src, but create a symbolic link to it and use that symbolic link, does that work properly? Wondering because making the Autoconf script simply generate a symlink might be a cleaner solution than moving the binary out if it works. (Or might not be, but it'd be useful to know just in case.)

**Comment by igilham** [comment]
The changes look good. Here's my shell session:

```shell
export PATH="$(brew --prefix gettext)/bin:$PATH"

./autogen.sh # <-- works
./configure # <-- works
make # <-- works

# run from src/
./src/starfighter 
Current directory "/Users/gilhai01/code/starfighter-origin/src"
ERROR: TTF_OpenFont: Couldn't open data/TakaoPGothic.ttf
Thank You for playing Starfighter

# symlink
ln -s src/starfighter starfighter
./starfighter # <-- works
```

**Comment by onpon4** [comment]
Alright, thank you! I've merged it in. 🙂

**Comment by igilham** [comment]
Cool, thanks

**Pull request merged**
